<?php require 'templates/header.phtml'; ?>

<h2>Viajes por Categoría</h2>

<?php if (!empty($items)): ?>
    <ul>
        <?php foreach ($items as $item): ?>
            <li>
                <h3>Origen: <?= htmlspecialchars($item->origen) ?> - Destino: <?= htmlspecialchars($item->destino) ?></h3>
                <p>Categoría: <?= htmlspecialchars($item->category_name) ?></p>
            </li>
        <?php endforeach; ?>
    </ul>
<?php else: ?>
    <p>No hay viajes disponibles para esta categoría.</p>
<?php endif; ?>

<button><a href="<?= BASE_URL ?>categories">Volver a Categorías</a></button>

<?php require 'templates/footer.phtml'; ?>
