<?php require_once "templates/header.phtml"; ?>

<nav>
    <a href="<?= BASE_URL ?>showLogin">Acceder como administrador</a>
</nav>

<h2>Nuestros Viajes</h2>


<form method="GET" action="<?= BASE_URL ?>filter-products">
    <label for="category_id">Filtrar por Categoría:</label>
    <select name="category_id" id="category_id">
        <option value="">Todas</option>
        <?php foreach ($categories as $category): ?>
            <option value="<?= htmlspecialchars($category->id) ?>">
                <?= htmlspecialchars($category->name) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <button type="submit">Filtrar</button>
</form>


<div>
    <?php if (!empty($viajes)): ?>
        <ul>
            <?php foreach ($viajes as $viaje): ?>
            <li>
                <div>
                    <h3>Origen: <?= htmlspecialchars($viaje->origen) ?> - Destino: <?= htmlspecialchars($viaje->destino) ?></h3>
                    <p>Servicio: <?= htmlspecialchars($viaje->category_name) ?></p>
                    <button><a href="<?= BASE_URL ?>product-details/<?= $viaje->id_viaje ?>">Ver detalles</a></button>
                </div>
            </li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <p>No hay viajes disponibles para la categoría seleccionada.</p>
    <?php endif; ?>
</div>

<button><a href="<?= BASE_URL ?>home">Volver al inicio</a></button>

<?php require_once "templates/footer.phtml"; ?>
